Repository FrankSauve/390AntennaPod, pull requests merged in 2018-02, with the labels that each got.

#56 Add to favorites, add to queue, mark as played/unplayed from the episodes pages
  README.md
  app/src/main/java/de/danoeh/antennapod/fragment/AllEpisodesFragment.java
Labels: [Organize podcasts], in review

#57 Organise podcast tests
  app/src/androidTest/java/de/test/antennapod/storage/FavoriteTest.java
  app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java
  core/src/androidTest/java/de/danoeh/antennapod/core/feed/FeedItemTest.java
Labels: in review, testing

#62 Refactored TrendingFragment and Load top list unit test
  app/src/androidTest/java/de/test/antennapod/itunes/ItunesApiTest.java
  app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
  app/src/main/java/de/danoeh/antennapod/fragment/TrendingFragment.java
Labels: [Trending tab], in review, refactor, testing
