Repository FrankSauve/390AntennaPod, pull requests merged in 2018-04, with the labels that each got.

#94 UI tests for autocomplete of regular, title and artist search
  app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java
Labels: [Autocomplete], testing

#107 Recommended for you feature
  app/src/androidTest/java/de/test/antennapod/discovery/DiscoveryTest.java
  app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java
  app/src/main/java/de/danoeh/antennapod/fragment/DiscoveryFragment.java
  app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
  app/src/main/java/de/danoeh/antennapod/preferences/PreferenceController.java
  core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
  core/src/main/res/values/arrays.xml
  core/src/main/res/values/strings.xml
Labels: [Recommended for you]

#116 Recommend fix
  app/src/main/java/de/danoeh/antennapod/fragment/DiscoveryFragment.java
  app/src/main/java/de/danoeh/antennapod/fragment/ItunesSearchFragment.java
Labels: [Recommended for you]

#110 Created home page in menu & added icon.
  app/build.gradle
  app/src/main/java/de/danoeh/antennapod/Model/SectionDataModel.java
  app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
  app/src/main/java/de/danoeh/antennapod/adapter/HomeRecyclerViewAdapter.java
  app/src/main/java/de/danoeh/antennapod/adapter/NavListAdapter.java
  app/src/main/java/de/danoeh/antennapod/adapter/ObjectListDataAdapter.java
  app/src/main/java/de/danoeh/antennapod/fragment/HomeFragment.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/home_list_item.xml
  app/src/main/res/layout/list_single_card.xml
  core/src/main/res/drawable-hdpi/ic_home_grey.png
  core/src/main/res/drawable-hdpi/ic_home_white.png
  core/src/main/res/drawable-mdpi/ic_home_grey.png
  core/src/main/res/drawable-mdpi/ic_home_white.png
  core/src/main/res/drawable-xhdpi/ic_home_grey.png
  core/src/main/res/drawable-xhdpi/ic_home_white.png
  core/src/main/res/drawable-xxhdpi/ic_home_grey.png
  core/src/main/res/drawable-xxhdpi/ic_home_white.png
  core/src/main/res/values/arrays.xml
  core/src/main/res/values/attrs.xml
  core/src/main/res/values/strings.xml
  core/src/main/res/values/styles.xml
Labels: [Home page]

#118 Automatic tweets on listen of a podcast
  app/build.gradle
  app/src/androidTest/java/de/test/antennapod/AntennaPodTestRunner.java
  app/src/androidTest/java/de/test/antennapod/twitter/TwitterTest.java
  app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/danoeh/antennapod/activity/MediaplayerActivity.java
  app/src/main/java/de/danoeh/antennapod/activity/authentication/GpodnetAuthenticationActivity.java
  app/src/main/java/de/danoeh/antennapod/activity/authentication/TwitterAuthenticationActivity.java
  app/src/main/java/de/danoeh/antennapod/service/TwitterService.java
  app/src/main/res/layout/twitterauth.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  core/src/main/java/de/danoeh/antennapod/core/preferences/UserPreferences.java
  core/src/main/res/values/strings.xml
Labels: [Share on social media]

#119 Added findbugs to circleCI
  app/build.gradle
  ci/script-findbugs.gradle
  circle.yml
  rules-findbugs.xml
Labels: CI

#124 The items on the homepage can now be clicked
  app/src/androidTest/java/de/test/antennapod/homepage/HomeTest.java
  app/src/main/java/de/danoeh/antennapod/activity/MainActivity.java
  app/src/main/java/de/danoeh/antennapod/adapter/HomeRecyclerViewAdapter.java
  app/src/main/java/de/danoeh/antennapod/adapter/ObjectListDataAdapter.java
  app/src/main/java/de/danoeh/antennapod/fragment/CompletedDownloadsFragment.java
  app/src/main/java/de/danoeh/antennapod/fragment/HomeFragment.java
Labels: [Home page]
